from setuptools import setup, find_packages

setup(
    name="knowledge-feed",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
       "appnope==0.1.4",
"asttokens==3.0.0",
"click==8.1.8",
"comm==0.2.2",
"debugpy==1.8.12",
"decorator==5.1.1",
"duckduckgo_search==7.3.2",
"exceptiongroup==1.2.2",
"executing==2.2.0",
"importlib_metadata==8.6.1",
"ipykernel==6.29.5",
"ipython==8.18.1",
"jedi==0.19.2",
"jupyter_client==8.6.3",
"jupyter_core==5.7.2",
"lxml==5.3.1",
"matplotlib-inline==0.1.7",
"nest-asyncio==1.6.0",
"packaging==24.2",
"parso==0.8.4",
"pexpect==4.9.0",
"platformdirs==4.3.6",
"primp==0.12.1",
"prompt_toolkit==3.0.50",
"psutil==7.0.0",
"ptyprocess==0.7.0",
"pure_eval==0.2.3",
"Pygments==2.19.1",
"python-dateutil==2.9.0.post0",
"pyzmq==26.2.1",
"six==1.17.0",
"stack-data==0.6.3",
"tornado==6.4.2",
"traitlets==5.14.3",
"typing_extensions==4.12.2",
"wcwidth==0.2.13",
"zipp==3.21.0",
    ],
    author="Your Name",
    author_email="your_email@example.com",
    description="Your package description",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Sandeep1904/knowledgefeed",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache License, Version 2.0",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.9",
)